<?php 
 $matriz_consoles = array
    (
      array(
          "PlayStation 4", 
          "Sony",
          "2013",
          "Um dos consoles mais vendidos da atualidade é a casa de diversos jogos aclamados pela crítica e por jogadores, como Bloodborne (2015), Uncharted 4: A Thief's End (2016), Uncharted: The Lost Legacy (2017) e Detroit: Become Human (2018).",
          "./img/ps4.png",
          "PlayStation 4 Slim",
          "./img/ps4pro.png",
          "PlayStation 4 PRO"
      ),
      array(
        "Switch",
        "Nintendo",
        "2017",
        "blablablalablablabla",
        "./img/nintendoswitch.png",
        "Nintendo Switch Standard",
        "./img/switch-lite.png",
        "Nintendo Switch Lite"
      ),
      array(
        "Nintendo 64",
        "Nintendo",
        "2017",
        "blablablalablablabla",
        "./img/N64.png",
        "Nintendo 64 Standard",
        "./img/N64-purple.png",
        "Nintendo 64 Grape Purple",
      ),
      array(
        "Xbox One",
        "Nintendo",
        "2017",
        "blablablalablablabla",
        "./img/xboxone.png",
        "Xbox One",
        "./img/xboxonex.png",
        "Xbox One X"
      ),
    ); 

    $matriz_empresas = array (
      array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
        array(
          "Jogos",

        ),
    );
?>